# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Continuous Integration .NET Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build ./templates/backend/server/DotnetTemplate.sln --configuration Debug 
    # - name: Pack the project
    #   run: dotnet test ./tests/DotNetTemplate.Tests/DotnetTemplate.sln --configuration Debug 
    - name: Pack NuGet package
      run: dotnet pack ./templates/backend/server/YourSolution.sln \
          --configuration Debug \
          --output ./nupkg \
    - name: Publish to NuGet.org
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
